#!/bin/bash

testHelpCreate() {
	vagueant --help | grep -q -- 'create - '
	status=$?
	assertEquals "--help should describe create" "0" "$status"
}

testCreate() {
	rm -rf ./tmp && mkdir -p ./tmp && cd ./tmp

	muter vagueant init

	# destroy the existing lxc, just in case
	muter lxc-stop -n tmp
	muter lxc-destroy -n tmp

	vagueant status | egrep -q 'not created'
	assertEquals "lxc should start 'not created'" "0" "$?"

	muter vagueant create
	assertEquals "vagueant create should exit with 0" "0" "$?"

	vagueant status | egrep -q 'poweroff'
	assertEquals "lxc should be created (poweroff'd)" "0" "$?"

	muter vagueant create
	assertEquals "create should be inert on secondary create" "0" "$?"

	cd .. && rm -rf ./tmp
}

