#!/bin/bash

testTemplate() {

    # First try adding and removing a non-existing template
    result=$(vagueant template add nonexistingtemplate)
    assertEquals "Show error message for incorrect template path" "ERROR: Please specify the full path to the template" "${result}"

    result=$(vagueant template remove nonexistingtemplate)
    assertEquals "Show error message for non existing template" "ERROR: Template 'nonexistingtemplate' does not exist. Use 'vaguant list' for a list of installed templates" "${result}"

    # Now add and remove a local template successfully
    muter vagueant template add `pwd`/lxc-test
    result=$(vagueant template list | grep lxc-test)
    assertEquals "lxc-test template should be installed" "lxc-test" "${result}"

    muter vagueant template remove lxc-test
    result=$(vagueant template list | grep lxc-test)
    assertEquals "lxc-test template should NOT be installed" "" "${result}"

    # Now add and remove a remote template successfully
    muter vagueant template add https://raw.github.com/frankscholten/vagueant/8735b588e9da44881da611c3373ff6126276ccbf/templates/lxc-ubuntu-puppet
    result=$(vagueant template list | grep lxc-ubuntu-puppet)
    assertEquals "lxc-ubuntu-puppet template should be installed" "lxc-ubuntu-puppet" "${result}"

    muter vagueant template remove lxc-ubuntu-puppet
    result=$(vagueant template list | grep lxc-ubuntu-puppet)
    assertEquals "lxc-ubuntu-puppet template should NOT be installed" "" "${result}"
}

