#!/bin/bash

testHelpStatus() {
	vagueant --help | grep -q -- 'status - '
	status=$?
	assertEquals "--help should describe status" "0" "$status"
}

testStatus() {
	return # TODO: finish this test
	rm -rf ./tmp && mkdir -p ./tmp && cd ./tmp

	vagueant init > /dev/null 2>&1

	vagueant status | egrep -q 'not created'
	assertEquals "lxc should start 'not created'" "0" "$?"

	cd .. && rm -rf ./tmp
}

