#!/bin/bash

testNoSuchCommand() {
	muter vagueant nosuchcommand
	assertEquals "broken commands should error" "1" "$?"

	vagueant nosuchcommand | grep -q "unknown command 'nosuchcommand'"
	assertEquals "broken commands should explain why they error" "0" "$?"
}

