#!/bin/bash

testHelpUp() {
	vagueant --help | grep -q -- 'up - '
	status=$?
	assertEquals "--help should describe up" "0" "$status"
}

testUp() {
	rm -rf ./tmp && mkdir -p ./tmp && cd ./tmp

	muter vagueant init

	# destroy the existing lxc, just in case
	muter lxc-stop -n tmp
	muter lxc-destroy -n tmp

	status=$(vagueant status)
	assertEquals "lxc should start 'not created'" "not created" "$status"

	muter vagueant up
	assertEquals "vagueant up should exit with 0" "0" "$?"

	status=$(vagueant status)
	assertEquals "lxc should be running" "running" "$status"

	cd .. && rm -rf ./tmp
}

