#!/bin/bash -e

cd "$(dirname "$0")"
testsdir="$PWD"

tests=()
verbose=false

# ensure /usr/local/bin is in PATH
export PATH="/usr/local/bin:$PATH"

# parse cli options
while true; do
	# quit if we're out of options
	[[ -z "$1" ]] && break
	
	case "$1" in
		--verbose)
			verbose=true
			;;
		*)
			tests+=("$1")
			;;
	esac

	# get next arg
	shift
done

# no tests specified? run all of them
if [[ 0 == ${#tests[@]} ]]; then
	tests=(./test_*)
fi

# Tests are split in to multiple files to keep them slightly more maintainable
# shunit2 doesn't seem to let me combine them well, so we cat them together
# and execute that instead.

tmp="$(mktemp)"

{
	# write out test header
	cat <<EOF
#!/bin/bash
verbose=$verbose
test_root="$PWD"

. "$testsdir"/helper_funcs
EOF
	
	# add in all the tests we need
	cat "${tests[@]}"
} > "$tmp"

bash shunit2 "$tmp"
rm -f "$tmp"
