#!/bin/bash -e

# Resets a Vagrant VM used by Vagueant for testing.
#
# Really dangerous, do not run on a machine you happen to like.

cd "$(dirname "$(dirname "$0")")"
vagueantdir="$PWD"

# Install any missing packages
pkgs=(lxc shunit2)
missing=()
for pkg in "${pkgs[@]}"; do
	if ! dpkg -s "$pkg" > /dev/null 2>&1; then
		missing+=("$pkg")
	fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
	apt-get update
	apt-get install -y "${missing[@]}"
fi

# Put a symlink to vagueant command so it's in $PATH
if [[ ! -h /usr/local/bin/vagueant ]]; then
	ln -s "$vagueantdir"/bin/vagueant /usr/local/bin/vagueant
fi
